"""empty message

Revision ID: 2d01f64959b0
Revises: 
Create Date: 2019-10-24 11:39:44.465519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d01f64959b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('off_days', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('competence', sa.String(length=5), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_age'), 'worker', ['age'], unique=False)
    op.create_index(op.f('ix_worker_availability'), 'worker', ['availability'], unique=False)
    op.create_index(op.f('ix_worker_competence'), 'worker', ['competence'], unique=False)
    op.create_index(op.f('ix_worker_first_name'), 'worker', ['first_name'], unique=False)
    op.create_index(op.f('ix_worker_last_name'), 'worker', ['last_name'], unique=False)
    op.create_index(op.f('ix_worker_off_days'), 'worker', ['off_days'], unique=False)
    op.create_index(op.f('ix_worker_position'), 'worker', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_position'), table_name='worker')
    op.drop_index(op.f('ix_worker_off_days'), table_name='worker')
    op.drop_index(op.f('ix_worker_last_name'), table_name='worker')
    op.drop_index(op.f('ix_worker_first_name'), table_name='worker')
    op.drop_index(op.f('ix_worker_competence'), table_name='worker')
    op.drop_index(op.f('ix_worker_availability'), table_name='worker')
    op.drop_index(op.f('ix_worker_age'), table_name='worker')
    op.drop_table('worker')
    # ### end Alembic commands ###
