"""empty message

Revision ID: a1ea33a80e2a
Revises: efc13680aa4d
Create Date: 2020-05-11 12:47:55.732630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ea33a80e2a'
down_revision = 'efc13680aa4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('slug', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_slug'), 'user', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_slug'), table_name='user')
    op.drop_column('user', 'slug')
    # ### end Alembic commands ###
